name: Checker

on:
  issues:
    types: [opened, reopened]

jobs:
  hw-checker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Cache pip
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies if not hit cache
        if: steps.pip-cache.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Answer
        uses: zhangt2333/action-judger@main
        with:
          script: |
            python main.py "${{ github.event.issue.body }}"